### ISSUE TITLE
4096 (0x1000) is an invalid culture identifier.

### ISSUE THREAD

**Issue by PeterSG-OLD** [PowerBiDevCamp/TranslationsBuilder#12]
Current Setup :  

I use the Version 2.0  with currently 3 cultures.  I exported the Current Fields into a CSV, imported it, and after i want rebuild the localized Table i getting this Error, but i can  create the translated objects table:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

```
************** Exception Text **************
System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'culture')
4096 (0x1000) is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(Int32 culture)
   at Microsoft.AnalysisServices.XmlaReader.ClientLocaleHelper..ctor(XmlaClient client)
   at Microsoft.AnalysisServices.XmlaReader.ClientLocaleHelper.SetupThreadUICultureToMatchXmlaRequest(XmlaClient xmlaClient)
   at Microsoft.AnalysisServices.XmlaReader.GetExtendedErrorInfo()
   at Microsoft.AnalysisServices.XmlaClient.ReadXmlaError(XmlReader reader)
   at Microsoft.AnalysisServices.XmlaClient.ReadXmlaMessages(XmlReader reader, XmlaMessageCollection xmlaMessages)
   at Microsoft.AnalysisServices.XmlaClient.CheckForException(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)
   at Microsoft.AnalysisServices.XmlaClient.ReadEmptyRoot(XmlReader reader, XmlaResult xmlaResult, Boolean skipResults)
   at Microsoft.AnalysisServices.XmlaClient.ReadEmptyRootS(XmlReader reader)
   at Microsoft.AnalysisServices.XmlaDataReader..ctor(XmlReader xmlReader, CommandBehavior commandBehavior, Boolean isXmlReaderAtRoot, IXmlaDataReaderOwner owner)
   at Microsoft.AnalysisServices.AmoDataReader..ctor(XmlReader xmlReader)
   at Microsoft.AnalysisServices.Core.Server.EndXmlaRequestWithReader(XmlaResultCollection& results)
   at Microsoft.AnalysisServices.Core.Server.ExecuteReader(String command, XmlaResultCollection& results, IDictionary properties, Boolean wrapCommand)
   at Microsoft.AnalysisServices.Tabular.ExecuteUtil.RunCommand(String commandText, Boolean requestImpact, Int64 impactSinceVersion, Server server, ImpactDataSet& impactDataSet)
   at Microsoft.AnalysisServices.Tabular.ExecuteUtil.TryExecuteXmla(Model model, String xmlaRequest, XmlaResultCollection& xmlaResults)
   at Microsoft.AnalysisServices.Tabular.Model.SaveChangesImpl(SaveOptions options)
   at Microsoft.AnalysisServices.Tabular.Model.SaveChanges(SaveOptions saveOptions)
   at Microsoft.AnalysisServices.Tabular.Model.SaveChanges()
   at TranslationsBuilder.Services.TranslationsManager.GenerateTranslatedLocalizedLabelsTable() in C:\DevCamp\TranslationsBuilder\TranslationsBuilder\Services\TranslationsManager.cs:line 1429
   at TranslationsBuilder.FormMain.GenerateTranslatedLocalizedLabelsTable(Object sender, EventArgs e) in C:\DevCamp\TranslationsBuilder\TranslationsBuilder\Forms\FormMain.cs:line 360
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```

**Comment by PeterSG-OLD** [comment]
Ok its happening because i use in Windows the Regional Format / en - DE  and the Default setup which the TB is pulling is en-EN

ok now the error is : 

Microsoft.AnalysisServices.OperationException: Failed to save modifications to the server. Error returned: 'CUSTOMDATA, USERNAME, USERCULTURE and USERPRINCIPALNAME functions are not supported in calculated tables/columns. These functions may only be used in Measures or in the AllowedRowsExpression.
