### ISSUE TITLE
Add new language / culture

### ISSUE THREAD

**Issue by ogaly-absys** [PowerBiDevCamp/TranslationsBuilder#3]
Hi,
thanks for this major update.
Is it possible to add a new language/culture?
In my Power BI dataset, I have this language fr-BE which is not present in the tool.

```
************** Texte de l'exception **************
System.Collections.Generic.KeyNotFoundException: The given key 'fr-BE' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TranslationsBuilder.Services.TranslationsManager.GetSecondaryCultureFullNamesInDataModel() in C:\DevCamp\TranslationsBuilder\TranslationsBuilder\Services\TranslationsManager.cs:line 415
   at TranslationsBuilder.FormMain.LoadModel() in C:\DevCamp\TranslationsBuilder\TranslationsBuilder\Forms\FormMain.cs:line 51
   at TranslationsBuilder.FormMain.onLoad(Object sender, EventArgs e) in C:\DevCamp\TranslationsBuilder\TranslationsBuilder\Forms\FormMain.cs:line 27
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by TedPattison** [comment]
I had to make some assumptions about how I designed this tool. One simplification I made was to only support one culture for each language. Therefore, you cannot add both **fr-FR** and **fr-BE** because both start with **fr**. I added the explicit set of languages and cultures that the tool supports.

I do not think it is possible for me to fix with issue without a large refactoring of how I have designed the language loading mechanism. Once way to deal with this would be for you to open the TranslationsBuilder project in Visual Studio where you could simply switch out **fr-FR** with **fr-BE**. You could use **fr-BE** as long it is the only culture for French that starts with "fr".

The other possibility is that I can extend Translations builder to allow you to configure the locale for a language. That way, the tool would let you do what you want with a simple configuration change.

Let me ask a question. If you are able to add **fr-BE**, would you ever need to add **fr-FR** or any other culture for French in addition to **fr-BE**? I assume the answer is no, but I wanted to ask just in case as that will affect what can be done to accommodate your scenario.

One more question, if you use **fr-FR** instead of **fr-BE**, what are the limitations/problems you experience?

**Comment by ogaly-absys** [comment]
Thank you for your response.

For my Power BI project, I use technical and formal conventions in English for measures and field names. 
I can manage the naming convention and let the clients handle naming customization.
I can change the customization on the fly without impacting existing reports based on the dataset.

My client is Belgian, and he wants the measures and fields to be named in French. For him, the **fr-FR** culture worked very well on Power BI Services but did not work on Excel when he wanted to analyze on Excel or on Power BI Desktop when he wanted to connect to the dataset.

After testing the translation on default culture and after on **fr-BE** culture, the client seen the same translation that mine. I concluded he has the **fr-BE** culture set up on his computer.

To be sure to have the same translation, I use the both culture **fr-FR** and **fr-BE** (I use default culture too).

For my use, I installed Translations builder, taken the source and modified the SupportedLanguages class. I created a new Language and added it in the AllLangauges dictionnary.
```
static public Language French = new Language { LanguageTag = "fr-FR", TranslationId = "fr", DisplayName = "French", NativeName = "Français", ShownOnlyOnExtendedLanguageList = false };
//new language FrenchBe  with TranslationId fr-be
static public Language FrenchBe = new Language { LanguageTag = "fr-BE", TranslationId = "fr-be", DisplayName = "FrenchBe", NativeName = "Français", ShownOnlyOnExtendedLanguageList = false };
...

 static public Dictionary<string, Language> AllLangauges =
           new Dictionary<string, Language>{
                        { Afrikaans.LanguageTag, Afrikaans },
              ...
             { French.LanguageTag, French },
             { FrenchBe.LanguageTag, FrenchBe },
             ...
             { Vietnamese.LanguageTag, Vietnamese }

    };

```
After compilation, I just replaced the Translations builder binary.

This is just a quick fix that only works for my use, but maybe it's possible to handle adding locale culture with configuration change

**Comment by TedPattison** [comment]
Hi all,
I have decided to extend Translations Builder to support a much wider set of languages and locales including the ability to add **fr-FR**, **fr-BE** and **fr-CA** in a single PBIX project. These changes will be introduced when I publish Translations Builder version 2.2. Let me know if you are interested in trying out a preview build of v2.2. My tentative schedule is to find a few people to test the changes and then publish the release of version 2.2 before the end of April.

**Comment by RetoWinti** [comment]
Hello Ted
As I am also affected by this problem, I would like to be available as a tester for the pre-release version 2.2.
Contact me if I can help.
