### ISSUE TITLE
Issue while translating with en-IN culture

### ISSUE THREAD

**Issue by jajinkya** [PowerBiDevCamp/TranslationsBuilder#4]
Thanks for the tool.

While using updated translation builder to build the multilingual report in power bi. I am facing following issue.
``System.Collections.Generic.KeyNotFoundException: The given key 'en-IN' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TranslationsBuilder.FormMain.LoadModel() in C:\DevCamp\TranslationsBuilder\TranslationsBuilder\Forms\FormMain.cs:line 48
   at TranslationsBuilder.FormMain.onLoad(Object sender, EventArgs e) in C:\DevCamp\TranslationsBuilder\TranslationsBuilder\Forms\FormMain.cs:line 29
``
I thought to change the culture of the `.pbix` file to `en-US` using tabular editor; but it is not allowing me to change. Is there any way to add these culture into translation builder or else to edit the culture of the existing `.pbix` file.

**Comment by Jejetator** [comment]
I do have the same issue with en-GB!
![image](https://user-images.githubusercontent.com/29051766/216009035-cf67ca50-c050-4813-a88e-5ad35812ae8d.png)

System.Collections.Generic.KeyNotFoundException: The given key 'en-GB' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TranslationsBuilder.FormMain.LoadModel() in C:\DevCamp\TranslationsBuilder\TranslationsBuilder\Forms\FormMain.cs:line 48
   at TranslationsBuilder.FormMain.onLoad(Object sender, EventArgs e) in C:\DevCamp\TranslationsBuilder\TranslationsBuilder\Forms\FormMain.cs:line 29
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Assemblys chargés **************
System.Private.CoreLib
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Private.CoreLib.dll
----------------------------------------
TranslationsBuilder
    Version de l'assembly : 2.0.0.0
    Version Win32 : 2.0
    CodeBase : file:///C:/Program%20Files/Power%20BI%20Dev%20Camp/Translations%20Builder/TranslationsBuilder.dll
----------------------------------------
System.Runtime
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.1322.60101
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.1322.60101
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Collections.Specialized.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.ObjectModel.dll
----------------------------------------
System.ComponentModel
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.ComponentModel.dll
----------------------------------------
System.Collections
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Collections.dll
----------------------------------------
System.Threading
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Threading.dll
----------------------------------------
System.Private.Uri
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Private.Uri.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Memory
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Memory.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Linq
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Linq.dll
----------------------------------------
System.Xml.ReaderWriter
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Private.Xml.dll
----------------------------------------
System.Text.RegularExpressions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Text.RegularExpressions.dll
----------------------------------------
System.Net.WebClient
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Text.Encoding.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Threading.Thread
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Threading.Thread.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Xml.XmlSerializer.dll
----------------------------------------
System.Drawing.Common
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/Microsoft.Win32.Primitives.dll
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 6.0.1322.60101
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/Accessibility.dll
----------------------------------------
System.Runtime.Loader
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.1322.60101
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/fr/System.Windows.Forms.resources.dll
----------------------------------------
System.Numerics.Vectors
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Collections.Concurrent.dll
----------------------------------------
System.Resources.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 6.0.2.0
    Version Win32 : 6.0.1322.60101
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.13/System.Drawing.dll
----------------------------------------
System.Collections.NonGeneric
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.AnalysisServices.Tabular
    Version de l'assembly : 19.51.0.0
    Version Win32 : 16.0.51.20
    CodeBase : file:///C:/Program%20Files/Power%20BI%20Dev%20Camp/Translations%20Builder/Microsoft.AnalysisServices.Tabular.dll
----------------------------------------
Microsoft.AnalysisServices.Core
    Version de l'assembly : 19.51.0.0
    Version Win32 : 16.0.51.20
    CodeBase : file:///C:/Program%20Files/Power%20BI%20Dev%20Camp/Translations%20Builder/Microsoft.AnalysisServices.Core.dll
----------------------------------------
Microsoft.AnalysisServices.Runtime.Core
    Version de l'assembly : 19.51.0.0
    Version Win32 : 16.0.51.20
    CodeBase : file:///C:/Program%20Files/Power%20BI%20Dev%20Camp/Translations%20Builder/Microsoft.AnalysisServices.Runtime.Core.dll
----------------------------------------
System.Runtime.Extensions
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Runtime.Extensions.dll
----------------------------------------
System.Data.Common
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Data.Common.dll
----------------------------------------
System.Net.ServicePoint
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Net.ServicePoint.dll
----------------------------------------
System.Net.Security
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Net.Security.dll
----------------------------------------
System.Runtime.Numerics
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Runtime.Numerics.dll
----------------------------------------
System.Net.NetworkInformation
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Net.NetworkInformation.dll
----------------------------------------
System.Diagnostics.Process
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Diagnostics.Process.dll
----------------------------------------
System.Console
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Console.dll
----------------------------------------
System.Net.Primitives
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Net.Primitives.dll
----------------------------------------
System.Management
    Version de l'assembly : 4.0.0.0
    Version Win32 : 7.0.22.51805
    CodeBase : file:///C:/Program%20Files/Power%20BI%20Dev%20Camp/Translations%20Builder/runtimes/win/lib/net6.0/System.Management.dll
----------------------------------------
Microsoft.Win32.Registry
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/Microsoft.Win32.Registry.dll
----------------------------------------
Microsoft.AnalysisServices.Runtime.Windows
    Version de l'assembly : 19.51.0.0
    Version Win32 : 16.0.51.20
    CodeBase : file:///C:/Program%20Files/Power%20BI%20Dev%20Camp/Translations%20Builder/Microsoft.AnalysisServices.Runtime.Windows.dll
----------------------------------------
System.Net.Requests
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Net.Requests.dll
----------------------------------------
System.Net.Http
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Net.Http.dll
----------------------------------------
System.Net.Sockets
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Net.Sockets.dll
----------------------------------------
System.Diagnostics.Tracing
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Diagnostics.Tracing.dll
----------------------------------------
System.Net.NameResolution
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Net.NameResolution.dll
----------------------------------------
System.Text.Json
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Text.Json.dll
----------------------------------------
System.IO.FileSystem
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.IO.FileSystem.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Diagnostics.StackTrace
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Diagnostics.Debug
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Diagnostics.Debug.dll
----------------------------------------
System.Xml.XDocument
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Xml.XDocument.dll
----------------------------------------
System.Private.Xml.Linq
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Private.Xml.Linq.dll
----------------------------------------
System.Resources.ResourceManager
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Resources.ResourceManager.dll
----------------------------------------
Microsoft.AnalysisServices.Tabular.resources
    Version de l'assembly : 19.51.0.0
    Version Win32 : 16.0.51.20
    CodeBase : file:///C:/Program%20Files/Power%20BI%20Dev%20Camp/Translations%20Builder/fr/Microsoft.AnalysisServices.Tabular.resources.dll
----------------------------------------
System.Reflection.Metadata
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Version de l'assembly : 6.0.0.0
    Version Win32 : 6.0.1322.58009
    CodeBase : file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.13/System.Collections.Immutable.dll
----------------------------------------

**Comment by jajinkya** [comment]
@Jejetator; you need to modify the translation builder code and add the required culture in the supported language class.
Have a look at it: https://github.com/PowerBiDevCamp/TranslationsBuilder/issues/3

**Comment by Jejetator** [comment]
Thanks, 
I'mn ot sure how to so that!
I played with my Laptop language, and also modified a pbit using tabular editor.
I'm no having this message which is even more disturbing ! 
![image](https://user-images.githubusercontent.com/29051766/216842945-cb515e81-4fac-46a3-bb9a-ea1ee7e8b158.png)

**Comment by jajinkya** [comment]
I think you have to add culture as en-US in the .pbix file using tabular editor. This might help you to connect to the translation builder.

**Comment by TedPattison** [comment]
Hi all,
I have decided to extend Translations Builder to support a much wider set of languages and locales including **en-IN**. These changes will be introduced when I publish Translations Builder version 2.2. Let me know if you are interested in trying out a preview build of v2.2. My tentative schedule is to find a few people to test the changes and then publish the release of version 2.2 before the end of March.

**Comment by jajinkya** [comment]
Yes, I would like to preview the build. Thank you.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
